
///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////

package design_1_AXI_DMA_0_pkg;

///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification
// environment.
///////////////////////////////////////////////////////////////////////////
  parameter design_1_AXI_DMA_0_ID                      = 0;
  parameter design_1_AXI_DMA_0_DMA_DATA_WIDTH_SRC      = 32;
  parameter design_1_AXI_DMA_0_DMA_DATA_WIDTH_DEST     = 32;
  parameter design_1_AXI_DMA_0_DMA_LENGTH_WIDTH        = 24;
  parameter design_1_AXI_DMA_0_DMA_2D_TRANSFER         = 0;
  parameter design_1_AXI_DMA_0_ASYNC_CLK_REQ_SRC       = 1;
  parameter design_1_AXI_DMA_0_ASYNC_CLK_SRC_DEST      = 1;
  parameter design_1_AXI_DMA_0_ASYNC_CLK_DEST_REQ      = 0;
  parameter design_1_AXI_DMA_0_AXI_SLICE_DEST          = 0;
  parameter design_1_AXI_DMA_0_AXI_SLICE_SRC           = 0;
  parameter design_1_AXI_DMA_0_SYNC_TRANSFER_START     = 1;
  parameter design_1_AXI_DMA_0_CYCLIC                  = 0;
  parameter design_1_AXI_DMA_0_DMA_AXI_PROTOCOL_DEST   = 0;
  parameter design_1_AXI_DMA_0_DMA_AXI_PROTOCOL_SRC    = 0;
  parameter design_1_AXI_DMA_0_DMA_TYPE_DEST           = 0;
  parameter design_1_AXI_DMA_0_DMA_TYPE_SRC            = 2;
  parameter design_1_AXI_DMA_0_DMA_AXI_ADDR_WIDTH      = 30;
  parameter design_1_AXI_DMA_0_MAX_BYTES_PER_BURST     = 128;
  parameter design_1_AXI_DMA_0_FIFO_SIZE               = 8;
  parameter design_1_AXI_DMA_0_AXI_ID_WIDTH_SRC        = 1;
  parameter design_1_AXI_DMA_0_AXI_ID_WIDTH_DEST       = 1;
  parameter design_1_AXI_DMA_0_DISABLE_DEBUG_REGISTERS = 0;
//////////////////////////////////////////////////////////////////////////

endpackage : design_1_AXI_DMA_0_pkg
