# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Files_XDC/DSP_Kintex_PM.xdc

# IP: ip/xfft_time_freq/xfft_time_freq.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_time_freq || ORIG_REF_NAME==xfft_time_freq} -quiet] -quiet

# IP: ip/axis_data_fifo_ifft/axis_data_fifo_ifft.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_ifft || ORIG_REF_NAME==axis_data_fifo_ifft} -quiet] -quiet

# IP: ip/axis_data_fifo_4/axis_data_fifo_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_4 || ORIG_REF_NAME==axis_data_fifo_4} -quiet] -quiet

# IP: ip/axis_data_fifo_fhy_defec/axis_data_fifo_fhy_defec.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_fhy_defec || ORIG_REF_NAME==axis_data_fifo_fhy_defec} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: ip/div_gen_0/div_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: ip/ifft_corr_1_1/ifft_corr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ifft_corr_1 || ORIG_REF_NAME==ifft_corr_1} -quiet] -quiet

# IP: ip/fft_corr_1/fft_corr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_corr_1 || ORIG_REF_NAME==fft_corr_1} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Concat_0/design_1_Concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Concat_0 || ORIG_REF_NAME==design_1_Concat_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_GND_0/design_1_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_GND_0 || ORIG_REF_NAME==design_1_GND_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_VCC_0/design_1_VCC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_VCC_0 || ORIG_REF_NAME==design_1_VCC_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_C2C_0/design_1_AXI_C2C_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_C2C_0 || ORIG_REF_NAME==design_1_AXI_C2C_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_C2C_axi_periph_0/design_1_AXI_C2C_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_C2C_axi_periph_0 || ORIG_REF_NAME==design_1_AXI_C2C_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_DMA_0/design_1_AXI_DMA_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_DMA_0 || ORIG_REF_NAME==design_1_AXI_DMA_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CLK_COMMON_0/design_1_CLK_COMMON_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_CLK_COMMON_0 || ORIG_REF_NAME==design_1_CLK_COMMON_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI_reset_0/design_1_AXI_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_reset_0 || ORIG_REF_NAME==design_1_AXI_reset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ibuf_0_0/design_1_ibuf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ibuf_0_0 || ORIG_REF_NAME==design_1_ibuf_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FPGA_reset_0/design_1_FPGA_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_FPGA_reset_0 || ORIG_REF_NAME==design_1_FPGA_reset_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LOGIC_1_0/design_1_LOGIC_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_LOGIC_1_0 || ORIG_REF_NAME==design_1_LOGIC_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TDD_SYNC4_0/design_1_TDD_SYNC4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TDD_SYNC4_0 || ORIG_REF_NAME==design_1_TDD_SYNC4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_fifo_ad9364_0_0/design_1_adc_fifo_ad9364_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_fifo_ad9364_0_0 || ORIG_REF_NAME==design_1_adc_fifo_ad9364_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dac_fifo_ad9364_0_0/design_1_dac_fifo_ad9364_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dac_fifo_ad9364_0_0 || ORIG_REF_NAME==design_1_dac_fifo_ad9364_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zero_sample_0/design_1_zero_sample_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zero_sample_0 || ORIG_REF_NAME==design_1_zero_sample_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_divclk_64_rst1_0/design_1_divclk_64_rst1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_divclk_64_rst1_0 || ORIG_REF_NAME==design_1_divclk_64_rst1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_ad9364_0/design_1_axi_ad9364_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_ad9364_0 || ORIG_REF_NAME==design_1_axi_ad9364_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LOGIC_1_1/design_1_LOGIC_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_LOGIC_1_1 || ORIG_REF_NAME==design_1_LOGIC_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TDD_SYNC1_0/design_1_TDD_SYNC1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TDD_SYNC1_0 || ORIG_REF_NAME==design_1_TDD_SYNC1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_fifo_ad9361_1_0/design_1_adc_fifo_ad9361_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_fifo_ad9361_1_0 || ORIG_REF_NAME==design_1_adc_fifo_ad9361_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dac_fifo_ad9361_1_0/design_1_dac_fifo_ad9361_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dac_fifo_ad9361_1_0 || ORIG_REF_NAME==design_1_dac_fifo_ad9361_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_1_0/design_1_RAshift16_4_up_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_1_0 || ORIG_REF_NAME==design_1_RAshift16_4_up_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_2_0/design_1_RAshift16_4_up_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_2_0 || ORIG_REF_NAME==design_1_RAshift16_4_up_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_3_0/design_1_RAshift16_4_up_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_3_0 || ORIG_REF_NAME==design_1_RAshift16_4_up_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_0_0/design_1_RAshift16_4_up_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_0_0 || ORIG_REF_NAME==design_1_RAshift16_4_up_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_ad9361_1_0/design_1_axi_ad9361_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_ad9361_1_0 || ORIG_REF_NAME==design_1_axi_ad9361_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TDD_SYNC2_0/design_1_TDD_SYNC2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TDD_SYNC2_0 || ORIG_REF_NAME==design_1_TDD_SYNC2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LOGIC_1_2/design_1_LOGIC_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_LOGIC_1_2 || ORIG_REF_NAME==design_1_LOGIC_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_fifo_ad9361_2_0/design_1_adc_fifo_ad9361_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_fifo_ad9361_2_0 || ORIG_REF_NAME==design_1_adc_fifo_ad9361_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dac_fifo_ad9361_2_0/design_1_dac_fifo_ad9361_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dac_fifo_ad9361_2_0 || ORIG_REF_NAME==design_1_dac_fifo_ad9361_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_1_1/design_1_RAshift16_4_up_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_1_1 || ORIG_REF_NAME==design_1_RAshift16_4_up_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_2_1/design_1_RAshift16_4_up_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_2_1 || ORIG_REF_NAME==design_1_RAshift16_4_up_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_3_1/design_1_RAshift16_4_up_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_3_1 || ORIG_REF_NAME==design_1_RAshift16_4_up_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_0_1/design_1_RAshift16_4_up_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_0_1 || ORIG_REF_NAME==design_1_RAshift16_4_up_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_ad9361_2_0/design_1_axi_ad9361_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_ad9361_2_0 || ORIG_REF_NAME==design_1_axi_ad9361_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TDD_SYNC3_0/design_1_TDD_SYNC3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TDD_SYNC3_0 || ORIG_REF_NAME==design_1_TDD_SYNC3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LOGIC_1_3/design_1_LOGIC_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_LOGIC_1_3 || ORIG_REF_NAME==design_1_LOGIC_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_fifo_ad9361_3_0/design_1_adc_fifo_ad9361_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_fifo_ad9361_3_0 || ORIG_REF_NAME==design_1_adc_fifo_ad9361_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dac_fifo_ad9361_3_0/design_1_dac_fifo_ad9361_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dac_fifo_ad9361_3_0 || ORIG_REF_NAME==design_1_dac_fifo_ad9361_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_0_2/design_1_RAshift16_4_up_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_0_2 || ORIG_REF_NAME==design_1_RAshift16_4_up_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_1_2/design_1_RAshift16_4_up_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_1_2 || ORIG_REF_NAME==design_1_RAshift16_4_up_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_2_2/design_1_RAshift16_4_up_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_2_2 || ORIG_REF_NAME==design_1_RAshift16_4_up_2_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RAshift16_4_up_3_2/design_1_RAshift16_4_up_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RAshift16_4_up_3_2 || ORIG_REF_NAME==design_1_RAshift16_4_up_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_ad9361_3_0/design_1_axi_ad9361_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_ad9361_3_0 || ORIG_REF_NAME==design_1_axi_ad9361_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_DSP_0/design_1_clk_DSP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_DSP_0 || ORIG_REF_NAME==design_1_clk_DSP_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DATA_rst_0/design_1_DATA_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_DATA_rst_0 || ORIG_REF_NAME==design_1_DATA_rst_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_const_0_0/design_1_const_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_const_0_0 || ORIG_REF_NAME==design_1_const_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_spi_0/design_1_axi_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_spi_0 || ORIG_REF_NAME==design_1_axi_spi_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cs_0_0/design_1_cs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cs_0_0 || ORIG_REF_NAME==design_1_cs_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cs_1_0/design_1_cs_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cs_1_0 || ORIG_REF_NAME==design_1_cs_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cs_2_0/design_1_cs_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cs_2_0 || ORIG_REF_NAME==design_1_cs_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cs_3_0/design_1_cs_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cs_3_0 || ORIG_REF_NAME==design_1_cs_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cs_4_0/design_1_cs_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cs_4_0 || ORIG_REF_NAME==design_1_cs_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_on_off_f1956_data_0/design_1_on_off_f1956_data_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_on_off_f1956_data_0 || ORIG_REF_NAME==design_1_on_off_f1956_data_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_on_off_f1956_clk_0/design_1_on_off_f1956_clk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_on_off_f1956_clk_0 || ORIG_REF_NAME==design_1_on_off_f1956_clk_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_MUX_0/design_1_SPI_MUX_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SPI_MUX_0 || ORIG_REF_NAME==design_1_SPI_MUX_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Control_from_SOM_0_0/design_1_Control_from_SOM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Control_from_SOM_0_0 || ORIG_REF_NAME==design_1_Control_from_SOM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Current_turning_off_0_0/design_1_Current_turning_off_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Current_turning_off_0_0 || ORIG_REF_NAME==design_1_Current_turning_off_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_1_0/design_1_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_1_0 || ORIG_REF_NAME==design_1_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_only_tx_0_0/design_1_only_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_only_tx_0_0 || ORIG_REF_NAME==design_1_only_tx_0_0} -quiet] -quiet

# IP: ip/xfft_time_freq/xfft_time_freq.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_time_freq || ORIG_REF_NAME==xfft_time_freq} -quiet] -quiet

# IP: ip/axis_data_fifo_ifft/axis_data_fifo_ifft.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_ifft || ORIG_REF_NAME==axis_data_fifo_ifft} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_2_0_1/design_1_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_2_0 || ORIG_REF_NAME==design_1_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_3_0/design_1_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_3_0 || ORIG_REF_NAME==design_1_xlconstant_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_3_1/design_1_xlconstant_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_3_1 || ORIG_REF_NAME==design_1_xlconstant_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_only_rx_0_0/design_1_only_rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_only_rx_0_0 || ORIG_REF_NAME==design_1_only_rx_0_0} -quiet] -quiet

# IP: ip/axis_data_fifo_4/axis_data_fifo_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_4 || ORIG_REF_NAME==axis_data_fifo_4} -quiet] -quiet

# IP: ip/axis_data_fifo_fhy_defec/axis_data_fifo_fhy_defec.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_fhy_defec || ORIG_REF_NAME==axis_data_fifo_fhy_defec} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: ip/div_gen_0/div_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: ip/xfft_time_freq/xfft_time_freq.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_time_freq || ORIG_REF_NAME==xfft_time_freq} -quiet] -quiet

# IP: ip/axis_data_fifo_ifft/axis_data_fifo_ifft.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_ifft || ORIG_REF_NAME==axis_data_fifo_ifft} -quiet] -quiet

# IP: ip/ifft_corr_1_1/ifft_corr_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ifft_corr_1 || ORIG_REF_NAME==ifft_corr_1} -quiet] -quiet

# IP: ip/fft_corr_1/fft_corr_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fft_corr_1 || ORIG_REF_NAME==fft_corr_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_switch_0_1/design_1_switch_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_switch_0_1 || ORIG_REF_NAME==design_1_switch_0_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
