set_property SRC_FILE_INFO {cfile:F:/work/Izhevsk_project_2_2/Izhevsk_project_2_2/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/constrs_1/imports/Files_XDC/DSP_Kintex_PM.xdc rfile:../../../Kintex_DSP_Lite.srcs/constrs_1/imports/Files_XDC/DSP_Kintex_PM.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports PIN_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H21 IOSTANDARD LVCMOS33} [get_ports PIN_1]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports PIN_2]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA24 IOSTANDARD LVCMOS33} [get_ports LED1]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports LED2]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS33} [get_ports LED3]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS33} [get_ports som_28v_en_link1]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD26 IOSTANDARD LVCMOS33} [get_ports som_28v_en_link2]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports som_28v_en_service1]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS33} [get_ports som_28v_en_service2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports som_28v_en_service3]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS33} [get_ports som_28v_en_service4]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB26 IOSTANDARD LVCMOS33} [get_ports som_5v_en_link]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports fpga_28v_en_link1]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS33} [get_ports fpga_28v_en_link2]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVCMOS33} [get_ports fpga_28v_en_service1]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V23 IOSTANDARD LVCMOS33} [get_ports fpga_28v_en_service2]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U26 IOSTANDARD LVCMOS33} [get_ports fpga_28v_en_service3]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V24 IOSTANDARD LVCMOS33} [get_ports fpga_28v_en_service4]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y25 IOSTANDARD LVCMOS33} [get_ports fpga_5v_en_link]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB24 IOSTANDARD LVCMOS33} [get_ports spi_cs_n_0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVCMOS33} [get_ports spi_sclk_0]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports spi_mosi_0]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA25 IOSTANDARD LVCMOS33} [get_ports spi_miso_0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC24 IOSTANDARD LVCMOS33} [get_ports spi_cs_n_1]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC23 IOSTANDARD LVCMOS33} [get_ports spi_sclk_1]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVCMOS33} [get_ports spi_mosi_1]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y26 IOSTANDARD LVCMOS33} [get_ports spi_miso_1]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9361_DCLK_1_P]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9361_DCLK_1_N]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9361_RX_FRAME1_P]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9361_RX_FRAME1_N]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_P[0]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_N[0]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_P[1]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_N[1]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_P[2]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_N[2]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_P[3]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_N[3]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_P[4]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_N[4]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_P[5]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P1_N[5]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9361_FB_CLK_1_P]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9361_FB_CLK_1_N]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9361_TX_FRAME1_P]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9361_TX_FRAME1_N]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_P[0]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_N[0]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_P[1]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_N[1]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_P[2]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_N[2]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_P[3]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_N[3]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_P[4]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_N[4]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_P[5]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9361_1_P0_N[5]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L24 IOSTANDARD LVCMOS18} [get_ports ad9361_EN_1]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS18} [get_ports ad9361_TXNRX_1]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K25 IOSTANDARD LVCMOS18} [get_ports ad9361_EN_AGC_1]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVCMOS18} [get_ports ad9361_RESET_1]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M26 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_CS_1]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_CLK_1]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_DI_1]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N26 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_DO_1]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA9 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_DCLK_2_P]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_DCLK_2_N]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC9 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_RX_FRAME2_P]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD9 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_RX_FRAME2_N]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD10 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_P[0]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE10 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_N[0]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE8 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_P[1]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF8 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_N[1]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF10 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_P[2]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF9 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_N[2]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD11 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_P[3]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE11 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_N[3]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE12 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_P[4]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF12 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_N[4]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_P[5]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P1_N[5]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_FB_CLK_2_P]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_FB_CLK_2_N]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_TX_FRAME2_P]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC11 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_TX_FRAME2_N]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_P[0]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W8 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_N[0]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_P[1]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_N[1]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_P[2]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_N[2]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W10 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_P[3]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_N[3]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_P[4]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_N[4]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_P[5]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y10 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_2_P0_N[5]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS18} [get_ports ad9361_EN_2]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R25 IOSTANDARD LVCMOS18} [get_ports ad9361_TXNRX_2]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS18} [get_ports ad9361_EN_AGC_2]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVCMOS18} [get_ports ad9361_RESET_2]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_CS_2]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P26 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_CLK_2]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_DI_2]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R26 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_DO_2]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_DCLK_3_P]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA2 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_DCLK_3_N]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_RX_FRAME3_P]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC2 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_RX_FRAME3_N]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_P[0]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_N[0]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_P[1]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V6 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_N[1]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_P[2]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_N[2]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_P[3]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_N[3]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_P[4]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_N[4]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_P[5]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W3 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P1_N[5]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC4 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_FB_CLK_3_P]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AC3 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_FB_CLK_3_N]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_TX_FRAME3_P]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AB4 IOSTANDARD LVDS DIFF_TERM 1} [get_ports ad9361_TX_FRAME3_N]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE6 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_P[0]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE5 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_N[0]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF5 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_P[1]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF4 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_N[1]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE3 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_P[2]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE2 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_N[2]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF3 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_P[3]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF2 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_N[3]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD1 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_P[4]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE1 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_N[4]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD4 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_P[5]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD3 IOSTANDARD LVDS DIFF_TERM 1} [get_ports {ad9361_3_P0_N[5]}]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS18} [get_ports ad9361_EN_3]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS18} [get_ports ad9361_TXNRX_3]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS18} [get_ports ad9361_EN_AGC_3]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R23 IOSTANDARD LVCMOS18} [get_ports ad9361_RESET_3]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_CS_3]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_CLK_3]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_DI_3]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVCMOS18} [get_ports ad9361_SPI_DO_3]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9364_DCLK_P]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9364_DCLK_N]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9364_RX_FRAME_P]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9364_RX_FRAME_N]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_P[0]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_N[0]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_P[1]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_N[1]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_P[2]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_N[2]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_P[3]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_N[3]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_P[4]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_N[4]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_P[5]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P1_N[5]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E11 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9364_FB_CLK_P]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9364_FB_CLK_N]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9364_TX_FRAME_P]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ad9364_TX_FRAME_N]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H9 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_P[0]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_N[0]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G10 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_P[1]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G9 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_N[1]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_P[2]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J10 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_N[2]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_P[3]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_N[3]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_P[4]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_N[4]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_P[5]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {ad9364_P0_N[5]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS18} [get_ports ad9364_EN]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVCMOS18} [get_ports ad9364_TXNRX]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P25 IOSTANDARD LVCMOS18} [get_ports ad9364_EN_AGC]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS18} [get_ports ad9364_RESET]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS18} [get_ports ad9364_SPI_CS]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N23 IOSTANDARD LVCMOS18} [get_ports ad9364_SPI_CLK]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS18} [get_ports ad9364_SPI_DI]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS18} [get_ports ad9364_SPI_DO]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports AXI_RX_CLK_OUT]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H26 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[0]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J26 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[1]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L23 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[2]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[3]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[4]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[5]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F25 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[6]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G24 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[7]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[8]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E23 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[9]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[10]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D26 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[11]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[12]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A24 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[13]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F24 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[14]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D25 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[15]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS33} [get_ports {AXI_RX_DATA_OUT[16]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVCMOS33} [get_ports AXI_TX_CLK_IN]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[0]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[1]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E26 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[2]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[3]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D23 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[4]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C26 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[5]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[6]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[7]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G26 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[8]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D24 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[9]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E25 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[10]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[11]}]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[12]}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[13]}]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B26 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[14]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B25 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[15]}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A23 IOSTANDARD LVCMOS33} [get_ports {AXI_TX_DATA_IN[16]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F22 IOSTANDARD LVCMOS33} [get_ports FPGA_REF_40MHZ]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/CLK_AXI/ibuf_0/inst/out_ref]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/AXI_Peripheral/AXI_C2C/inst/master_fpga_gen.axi_chip2chip_master_phy_inst/master_sio_phy.axi_chip2chip_sio_input_inst/axi_chip2chip_clk_gen_inst/clk_in_ibufg]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_AD9361_2
add_cells_to_pblock [get_pblocks pblock_AD9361_2] [get_cells -quiet [list design_1_i/AD9361_CTRL/AD9361_2]]
resize_pblock [get_pblocks pblock_AD9361_2] -add {SLICE_X136Y51:SLICE_X153Y99}
resize_pblock [get_pblocks pblock_AD9361_2] -add {RAMB18_X6Y22:RAMB18_X6Y39}
resize_pblock [get_pblocks pblock_AD9361_2] -add {RAMB36_X6Y11:RAMB36_X6Y19}
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_AD9361_3
add_cells_to_pblock [get_pblocks pblock_AD9361_3] [get_cells -quiet [list design_1_i/AD9361_CTRL/AD9361_3]]
resize_pblock [get_pblocks pblock_AD9361_3] -add {SLICE_X136Y100:SLICE_X153Y149}
resize_pblock [get_pblocks pblock_AD9361_3] -add {RAMB18_X6Y40:RAMB18_X6Y59}
resize_pblock [get_pblocks pblock_AD9361_3] -add {RAMB36_X6Y20:RAMB36_X6Y29}
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
create_pblock AXI_BRIDGE
add_cells_to_pblock [get_pblocks AXI_BRIDGE] [get_cells -quiet [list design_1_i/AXI_Peripheral/AXI_C2C design_1_i/AXI_Peripheral/AXI_C2C_axi_periph design_1_i/AXI_Peripheral/AXI_DMA]]
resize_pblock [get_pblocks AXI_BRIDGE] -add {SLICE_X0Y100:SLICE_X23Y149}
resize_pblock [get_pblocks AXI_BRIDGE] -add {DSP48_X0Y40:DSP48_X1Y59}
resize_pblock [get_pblocks AXI_BRIDGE] -add {RAMB18_X0Y40:RAMB18_X1Y59}
resize_pblock [get_pblocks AXI_BRIDGE] -add {RAMB36_X0Y20:RAMB36_X1Y29}
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_AD9364
add_cells_to_pblock [get_pblocks pblock_AD9364] [get_cells -quiet [list design_1_i/AD9364]]
resize_pblock [get_pblocks pblock_AD9364] -add {SLICE_X0Y200:SLICE_X13Y249}
resize_pblock [get_pblocks pblock_AD9364] -add {DSP48_X0Y80:DSP48_X0Y99}
resize_pblock [get_pblocks pblock_AD9364] -add {RAMB18_X0Y80:RAMB18_X0Y99}
resize_pblock [get_pblocks pblock_AD9364] -add {RAMB36_X0Y40:RAMB36_X0Y49}
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_AD9361_1
add_cells_to_pblock [get_pblocks pblock_AD9361_1] [get_cells -quiet [list design_1_i/AD9361_CTRL/AD9361_1]]
resize_pblock [get_pblocks pblock_AD9361_1] -add {SLICE_X0Y150:SLICE_X13Y199}
resize_pblock [get_pblocks pblock_AD9361_1] -add {DSP48_X0Y60:DSP48_X0Y79}
resize_pblock [get_pblocks pblock_AD9361_1] -add {RAMB18_X0Y60:RAMB18_X0Y79}
resize_pblock [get_pblocks pblock_AD9361_1] -add {RAMB36_X0Y30:RAMB36_X0Y39}
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_SPI_MOD
add_cells_to_pblock [get_pblocks pblock_SPI_MOD] [get_cells -quiet [list design_1_i/SPI_MOD]]
resize_pblock [get_pblocks pblock_SPI_MOD] -add {SLICE_X0Y75:SLICE_X13Y99}
resize_pblock [get_pblocks pblock_SPI_MOD] -add {DSP48_X0Y30:DSP48_X0Y39}
resize_pblock [get_pblocks pblock_SPI_MOD] -add {RAMB18_X0Y30:RAMB18_X0Y39}
resize_pblock [get_pblocks pblock_SPI_MOD] -add {RAMB36_X0Y15:RAMB36_X0Y19}
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins design_1_i/CLK_AXI/CLK_COMMON/inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks prm_clk_ad1]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins design_1_i/CLK_AXI/CLK_COMMON/inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks prm_clk_ad2]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins design_1_i/CLK_AXI/CLK_COMMON/inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks prm_clk_ad3]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins design_1_i/CLK_AXI/CLK_COMMON/inst/mmcm_adv_inst/CLKOUT1]] -group [get_clocks prm_clk_ad4]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_IP_sync_0
resize_pblock [get_pblocks pblock_IP_sync_0] -add {CLOCKREGION_X0Y0:CLOCKREGION_X1Y6}
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/AD9361_CTRL/ad9361_clk/clk_DSP/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins design_1_i/CLK_AXI/CLK_COMMON/inst/mmcm_adv_inst/CLKOUT1]]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/CLK_AXI/CLK_COMMON/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins design_1_i/AD9361_CTRL/ad9361_clk/clk_DSP/inst/mmcm_adv_inst/CLKOUT0]]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/AD9361_CTRL/ad9361_clk/clk_DSP/inst/mmcm_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0]]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_pins {design_1_i/vio_0/inst/PROBE_OUT_ALL_INST/G_PROBE_OUT[4].PROBE_OUT0_INST/Probe_out_reg[0]/C}] -to [get_pins {design_1_i/only_rx_0/inst/DeFEC_sub/dec/engine/cnode/engine_inst_c_gen[0].engine_inst_llra_gen[2].engine/obusy_reg/CLR}] 1
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT1]]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT1]]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT1]]
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT1]]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins design_1_i/clk_wiz_0/inst/plle2_adv_inst/CLKOUT0]]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/AD9361_CTRL/ad9361_clk/clk_DSP/inst/sample_rate_30_72]]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[0]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[1]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[2]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[3]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[4]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[5]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[6]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[7]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[8]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[9]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[10]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_q[11]}]]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[0]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[1]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[2]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[3]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[4]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[5]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[6]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[7]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[8]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[9]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[10]} {design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/osub_i[11]}]]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 18 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[0]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[1]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[2]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[3]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[4]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[5]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[6]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[7]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[8]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[9]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[10]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[11]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[12]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[13]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[14]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[15]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[16]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_ifft_q_reg_1[17]}]]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[0]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[1]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[2]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[3]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[4]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[5]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[6]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[7]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[8]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[9]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[10]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[11]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[12]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[13]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[14]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[15]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[16]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[17]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[18]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[19]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[20]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[21]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[22]} {design_1_i/only_rx_0/inst/RX_phy_sub/xcorr_main_sub/data_abs_mx[23]}]]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/only_rx_0/inst/RX_phy_sub/equalizer_sub/oval]]
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
