# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/work/Izhevsk_project_2_1/Izhevsk_project_2_1/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_only_tx_0_0/design_1_only_tx_0_0.xci
# IP: The module: 'design_1_only_tx_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: F:/work/Izhevsk_project_2_1/Izhevsk_project_2_1/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/xfft_time_freq/xfft_time_freq.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_time_freq || ORIG_REF_NAME==xfft_time_freq} -quiet] -quiet

# IP: F:/work/Izhevsk_project_2_1/Izhevsk_project_2_1/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/axis_data_fifo_ifft/axis_data_fifo_ifft.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_ifft || ORIG_REF_NAME==axis_data_fifo_ifft} -quiet] -quiet

# XDC: f:/work/Izhevsk_project_2_1/Izhevsk_project_2_1/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_only_tx_0_0/design_1_only_tx_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_only_tx_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: F:/work/Izhevsk_project_2_1/Izhevsk_project_2_1/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_only_tx_0_0/design_1_only_tx_0_0.xci
# IP: The module: 'design_1_only_tx_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: F:/work/Izhevsk_project_2_1/Izhevsk_project_2_1/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/xfft_time_freq/xfft_time_freq.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_time_freq || ORIG_REF_NAME==xfft_time_freq} -quiet] -quiet

# IP: F:/work/Izhevsk_project_2_1/Izhevsk_project_2_1/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/ip/axis_data_fifo_ifft/axis_data_fifo_ifft.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_ifft || ORIG_REF_NAME==axis_data_fifo_ifft} -quiet] -quiet

# XDC: f:/work/Izhevsk_project_2_1/Izhevsk_project_2_1/projects/Kintex_DSP_Lite/Kintex_DSP_Lite.srcs/sources_1/bd/design_1/ip/design_1_only_tx_0_0/design_1_only_tx_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_only_tx_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
